version: '3.7'

services:

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: php-ticket
    volumes:
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../TicketCRM_app:/var/www/html
    user: user
    command: php-fpm --nodaemonize
    networks:
      network-ticket:
        aliases:
          - php
    environment:
      DB_PORT: 3306
      DB_HOST: database

  nginx:
    build:
      context: docker/nginx
    container_name: nginx-ticket
    ports:
      - 80:8083
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      network-ticket:
        aliases:
          - api.ticket.loc
          - admin.ticket.loc
    user: user
    command: [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ]

  database:
    image: mysql:5.7
    container_name: database-ticket
    ports:
      - 33065:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/mysqlConfig/log/mysql.log:/var/log/mysql/mysql.log
      - ./docker/mysqlConfig/my.cnf:/etc/mysql/my.cnf
    networks:
      network-ticket:
        aliases:
          - database
    environment:
      MYSQL_ROOT_PASSWORD: common404
      MYSQL_DATABASE: laravel

  node:
    build:
      context: docker/node
    working_dir: /var/app
    ports:
      - 8081:8080
    volumes:
      - ../TicketCRM_front:/var/app
    user: node
    command: tail -f /dev/null

networks:
  network-ticket:

volumes:
  php-socket-ticket:
